### ISSUE TITLE
Pagination number does not persist when routing to other pages

### ISSUE THREAD

**Issue by spettway** [spettway/canary#8]
#### Description
The pagination always resets to page 1 of reviews when the user goes to another page then returns (e.g. if the user goes to "Write a Review" then comes back or clicks on a review and then goes back home)

#### Files
[home.tsx
](https://github.com/spettway/canary/blob/f2f010a8ca4d1224e7b146b3ca7b0e868a862df1/src/pages/Home.tsx)
#### To Reproduce
Click on page 5. Click on a review. Return back to previous screen. Pagination will be reset to page 1 of reviews

**Comment by grantw99** [comment]
You can assign this to me, I have a fix just need permission to push a branch so I can make a PR and then it should be fixed.  I just moved the state that held the page number into the app page and then passed it and the state assignment function in as props into the home page which allows the pagination position to persist as desired.

**Comment by grantw99** [comment]
Issue has been resolved and pagination persists on website now
